name: Scheduled Release

on:
  push

env:
    Change_Freeze: false

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - name: Change Freeze Implemented 
        if: env.Change_Freeze != 'false'
        run: echo "Scheduled Releases can only be published during approved maintenance windows."

      - id: release
        uses: rymndhng/release-on-push-action@master
        if: env.Change_Freeze == 'false'
        with:
          # increments the patch version by 1. e.g. 1.0.0 > 1.0.1
          bump_version_scheme: patch
          use_github_release_notes: true
      
      - id: outputs
        name: Check Output Parameters
        run: |
          echo "Got tag name ${{ steps.release.outputs.tag_name }}"
          echo "Got release version ${{ steps.release.outputs.version }}"

      - id: Sleep
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'

      - id: fetch-latest-release
        uses: thebritican/fetch-latest-release@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - id: publish
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.fetch-latest-release.outputs.id }}
